### ISSUE TITLE
Upload artifact to Sonatype

### ISSUE THREAD

**Issue by mbastian** [linkedin/PalDB#1]

**Comment by sankethkatta** [comment]
Looks like its possible to push to Sonatype via Travis: http://benlimmer.com/2014/01/04/automatically-publish-to-sonatype-with-gradle-and-travis-ci/

**Comment by mbastian** [comment]
Yes, that's what I intend to do! Just waiting some LinkedIn admin enables this repository on Travis ;)

Thanks for the pointer, I knew how to do it for Maven but that describes the Gradle way

**Comment by AshwinJay** [comment]
Are you planning to make this available on the Maven repo? Thanks.

**Comment by anand-singh** [comment]
+1

Thanks,
Anand

**Comment by mbastian** [comment]
Finally resolved the auth issues, so done: https://oss.sonatype.org/content/repositories/releases/com/linkedin/paldb/paldb/1.1.0/
