### ISSUE TITLE
java.io.IOException: 试图将文件指针移到文件开头之前。

### ISSUE THREAD

**Issue by haochun** [linkedin/PalDB#11]
i am a china developer.when i use PalDB,i occured some problem:

Caused by: java.io.IOException: 试图将文件指针移到文件开头之前。
	at java.io.RandomAccessFile.setLength(Native Method)
	at com.linkedin.paldb.impl.StorageWriter.buildIndex(StorageWriter.java:282)
	at com.linkedin.paldb.impl.StorageWriter.close(StorageWriter.java:183)
	at com.linkedin.paldb.impl.WriterImpl.close(WriterImpl.java:100)

my develop os is windows10

**Comment by haochun** [comment]
i know the cause:
because i store about 75,000,000 k/v,the problem happed in the last rows below:

 long count = keyCounts[keyLength];
    int slots = (int) Math.round(count / loadFactor);
    int offsetLength = maxOffsetLengths[keyLength];
    int slotSize = keyLength + offsetLength;

    // Init index
    File indexFile = new File(tempFolder, "index" + keyLength + ".dat");
    RandomAccessFile indexAccessFile = new RandomAccessFile(indexFile, "rw");
    indexAccessFile.setLength(slots * slotSize);


the slotSize more than Integer.MAX_VALUE,mayse change like this:

long slotSize = Long.valueOf(keyLength) +  Long.valueOf(offsetLength);


can i pull a request?

**Comment by haochun** [comment]
sorry,i does not read the README.md careful.PalDB does not support more than 2GB now.so i does not need to pull a request.i hope you update it to support more than 2GB!

**Comment by wanggaohang** [comment]
真逗。。
