### ISSUE TITLE
request for doc clarifications

### ISSUE THREAD

**Issue by phraktle** [linkedin/PalDB#2]
Hi Mathieu,

Interesting project, thanks for open sourcing it! Could you please clarify the following (here or in the documentation)?

 * can you open a db for writing subsequent times?
 * what's the concurrency story? (e.g. concurrent writers, reads while writers are in progress, are readers lock/wait-free, etc) 
 * when inserting duplicate keys, does it just throw an exception? 
 * is it just a hash table, or does the data structure support sorted iteration?
 * what's your target java version?

Thanks,
  Viktor

**Comment by mbastian** [comment]
All good suggestions, I'll clarify this asap. Thanks

**Comment by mbastian** [comment]
I'll update the documentation but in the meantime:

> can you open a db for writing subsequent times?

No, the final binary file is created when StoreWriter.close() is called.

> what's the concurrency story? (e.g. concurrent writers, reads while writers are in progress, are readers lock/wait-free, etc)

Concurrency support is non-existent at this point but I plan to make reading and writing thread-safe. Users shouldn't try to put/get values from multiple threads a this point. Note that there's no problem writing and reading stores in parallel as long as there's a unique thread per store and you have enough off-heap memory to handle it. Creating multiple readers on the same underlying store may actually work but I haven't tested it.

> when inserting duplicate keys, does it just throw an exception?

Yes, duplicate keys aren't allowed.

> is it just a hash table, or does the data structure support sorted iteration?

It's basically a hashtable, you can iterate the store but there's no order.

> what's your target java version?

Compatible 1.6 and above.

**Comment by mbastian** [comment]
Added a new FAQ section on readme. The concurrency question is addressed in limitations at this point.
